name: api_client_plus_example
description: "Demonstrates how to use the api_client_plus plugin."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  api_client_plus:
    path: ../

dev_dependencies:
  device_info_plus: ^10.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  connectivity_plus: ^7.0.0

flutter:
  uses-material-design: true
